proyectos/noticias/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #El primer nombre "Home" es lo que va en el url www.algo/"algo" esto me va a llevar a la acción home del staticpages
  get 'home', to: 'static_pages#home'
  get 'dashboard', to: 'users#dashboard'

  resources :notices, only: [:index, :show]
  namespace :admin do
    resources :notices
  end

  resources :comments, only: [:create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
end

proyectos/noticias/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

proyectos/noticias/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :notice
end

proyectos/noticias/app/models/notice.rb
class Notice < ApplicationRecord
  extend FriendlyId
  friendly_id :titulo, use: :slugged #url-titulo: notices-algo != noticas/1
  has_many :comments
  belongs_to :user

end

proyectos/noticias/app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, stretches: 3

  has_many :comments
  has_many :notices
end

proyectos/noticias/app/controllers/admin/notices_controller.rb
#Este controlador es totalmente independiente de notice Controller, tiene vistas por separado y todos los métodos no puedo
# acceder desde el otro lado!
class Admin::NoticesController < ApplicationController
  before_action :authenticate_user!
  before_action :validar_admin

  before_action :find_comment, only: [:show, :edit, :update, :destroy]

  #Métodos de crear y editar... y eliminar
  #HOME
  def index
    @notices = Notice.all #para tener acceso a la vista, @prudcos es como que global

  end

  #MOSTRAR
  def show
    #Ya lo está haciendo el before action de find_comment y en el método private está definido!
    #@notice = Notice.friendly.find(params[:id]) #solo los detalles del producto (id)
    #@producto = Producto.where( id: params[:id]) #query a la base de datos, trae los productos que tengan un id con el parametro id del url

  end

  #CREAR
  def new
    @notice = Notice.new #esto me en necesario para instanciar un objeto al momento de que cargue el crear, si no tengo nada creado aun, no me puede dar error

  end

  def create
    @notice = Notice.new(notice_params)
    #@notice.proveedor = Proveedor.first
    if @notice.save
      flash[:notice] = "Registro Exitoso!"
      redirect_to admin_notice_path(@notice) #Esto me redirecciona al new
    else
      render 'new'
    end

  end

  #EDITAR
  def edit
    #Pasa igual que con el showw !
    #@notice = Notice.friendly.find(params[:id])

  end

  def update

    if @notice.update(notice_params)
      flash[:notice] = "Modificado con exito!"
      redirect_to admin_notice_path(@notice)
    else
      render 'edit'
    end

  end

  #ELIMINAR
  def destroy

    @notice.destroy
    redirect_to admin_notices_path
  end

  #Método privado: solo acceden los métodos dentro de este contriller
  private
  def notice_params
    params.require(:notice).permit(:titulo, :descripcion_corta, :descripcion_larga, :user_id) #De los parametros que voy a recibir, revisa que siempre venga un parámetro de estos
    #luego de validar, permite que el usuario grabe el nombre y la descripcion
  end

  def validar_admin
    unless current_user.admin
      redirect_to dashboard_path
    end
  end

  def find_comment
    @notice = Notice.friendly.find(params[:id])

  end


end

proyectos/noticias/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(user)
    dashboard_path()
  end

end

proyectos/noticias/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comments = Comment.new
  end

  def create
    @comment = Comment.new(comments_params)
    puts @comment
    if @comment.save
      flash[:notice] = "Registro Exitoso!"
      redirect_to notice_path(@comment.notice)
    else
      flash[:notice] = "Error el guardar..."
      redirect_to notice_path(@comment.notice)
    end

  end
  private
  def comments_params
    params.require(:comment).permit(:user_id, :notice_id, :comentarios)
  end

end

proyectos/noticias/app/controllers/notices_controller.rb
#Este controlador es totalmente independiente de notice Controller (del admin), tiene vistas por separado y todos los métodos no puedo
# acceder desde el otro lado!
class NoticesController < ApplicationController

  #Métodos de ver...

  def index
    @notices = Notice.all
  end

  def show
    @notice = Notice.friendly.find(params[:id])
    @coment = @notice.comments  #comentsrios de esta notica
    @comentario = Comment.new #agrega el formulario de comentarios directo en la págian del swho

  end

end

proyectos/noticias/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    #cuando alguien entre a www.algo este va a ser mi
    # página de inicio, no tiene variable, pero si vista
    # mi vista se llama igual que mi accion (home)
    @name = current_user.present? ? current_user.email : 'Desconocido'
    #<!--Si existe current_user, ponle el email! de lo contrario, ponle desconocido!-->
    # <!--el método present se escribe así: present?, y los métodos terneatios son con ?-->
    # Este es un controlador sin base de datos, o sea solo maneja  vistas, por tanto no necsita modelo
  end
  #Cada controlador debe tener carpeta dentro de Viws
  #Para cada accion debe haber una vista!


end

proyectos/noticias/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  #Cundo inicio sesión sesion me voy al home, pero de loegeado
  # En cada aplicación tengo una vista, y esa vista es el root
  # cuando inicio sesión.. me bota al... dashboard (un lugar inicial)
  def dashboard
    #current_user.notices todas las notiicas qu creó el usuario actual
    #current_user.comments todos los comentarios de ese usuario
    @notice = Notice.all
    @user = User.all
    #@notice_admin = User.all.select {|tipo| tipo.admin?}
    @users_admin = User.where(admin: true)
    @no_users_admin = User.where(admin: false)
    @noticias_uniqs = Comment.where(user_id: current_user.id).map(&:notice_id).uniq
    @coments = Comment.all
    @commets_x_notice = Comment.where(user_id: current_user.id).map(&:notice_id)
    @commts_user = Comment.where(user_id: current_user.id)


    @ultimo_comentario = Comment.where(user_id: current_user.id).last
    #@fecha_ultimo_comentario = Comment.where(user_id: current_user.id).last.updated_at
    #@noticia_ultimo_comentrio = Comment.where(user_id: current_user.id).last.notice_id

    #@user_final = User.last
    #@ultimo_comentario_usuario = @coments.where(user_id: @user_final.id)

  end


end

proyectos/noticias/app/helpers/admin/notices_helper.rb
module Admin::NoticesHelper
end

proyectos/noticias/app/helpers/application_helper.rb
module ApplicationHelper
end

proyectos/noticias/app/helpers/comments_helper.rb
module CommentsHelper
end

proyectos/noticias/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

proyectos/noticias/app/helpers/users_helper.rb
module UsersHelper


end

proyectos/noticias/app/views/admin/notices/edit.html.erb
<!--Crear es muy similar a editar, me traigo lo mismo-->
<h1>Edita un producto</h1>

<% if @notice.errors.any? %>
  <h4>Hubo errores con la editación, revisa que...</h4>
  <ul>
    <% @notice.errors.full_messages.each do |errores| %>
      <li><%= errores %></li>
    <% end %>
  </ul>
<% end %>


<!--modelo accede a la variable-->
<!--el formulario es más como para registros, estoy en la vista new, y como llego a crear?-->
<!--lcal true: el rato que doy submit, va ahacer peticion para, como para decir que es local y no una llamada js-->
<%= form_with(model: [:admin, @notice], local: true) do |elemento| %>

  <%= elemento.hidden_field :user_id, value: current_user.id %>

  <p>
    <%= elemento.label :titulo %>
    <%= elemento.text_field :titulo %>
  </p>

  <p>
    <%= elemento.label :descripcion_corta %>
    <%= elemento.text_field :descripcion_corta %>
  </p>

  <p>
    <%= elemento.label :descripcion_larga %>
    <%= elemento.text_field :descripcion_larga %>
  </p>

  <%= elemento.submit "Guardar"  %>

<% end %>

<%= link_to "cancelar y volver", admin_notices_path %>

proyectos/noticias/app/views/admin/notices/index.html.erb
<!--Listado de noticias-->
<!--ver una noticia en particular-->
<!--Paso 13-->

<h1>TFC Smart</h1>
<h5>ESFOT-EPN</h5>

<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th>Noticia</th>
    <th>Descripcion Corta</th>
    <th colspan="3">Descripcion Larga</th>
  </tr>
  </thead>

  <tbody>
  <% @notices.each do |noticia| %>
    <tr>
      <td><%= noticia.titulo %></td>
      <td><%= noticia.descripcion_corta %></td>
      <td><%= noticia.descripcion_larga %></td>
      <td>
        <%= link_to "detalle", admin_notice_path(noticia.id) %>
        <%= link_to "editar", edit_admin_notice_path(noticia) %>
        <%= link_to "borrar", admin_notice_path(noticia), method: :delete, data: { confirmar: "Estas seguro?"} %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<h4>Agregar otra noticias: <%= link_to "nuevo", new_admin_notice_path %> </h4>

proyectos/noticias/app/views/admin/notices/new.html.erb
<!--Liks para crear y editar y eliminar noticias :) -->
<h1>Crea una noticia</h1>

<% if @notice.errors.any? %>
  <h4>Hubo errores con el registro, revisa que...</h4>
  <ul>
    <% @notice.errors.full_messages.each do |errores| %>
      <li><%= errores %></li>
    <% end %>
  </ul>
<% end %>


<!--modelo accede a la variable-->
<!--el formulario es más como para registros, estoy en la vista new, y como llego a crear?-->
<!--lcal true: el rato que doy submit, va ahacer peticion para, como para decir que es local y no una llamada js-->
<%= form_with model: [:admin, @notice], local: true do |elemento| %>

  <%= elemento.hidden_field :user_id, value: current_user.id %>

  <p>
    <%= elemento.label :titulo %>
    <%= elemento.text_field :titulo %>
  </p>

  <p>
    <%= elemento.label :descripcion_corta %>
    <%= elemento.text_field :descripcion_corta %>
  </p>

  <p>
    <%= elemento.label :descripcion_larga %>
    <%= elemento.text_field :descripcion_larga %>
  </p>


  <%= elemento.submit "Guardar"  %>

<% end %>

<%= link_to "volver", admin_notices_path %>

proyectos/noticias/app/views/admin/notices/show.html.erb
<h1>Detalle: </h1>
<h4><strong>Título: </strong><%= @notice.titulo %></h4>
<h4><strong>Descripcion: </strong><%= @notice.descripcion_corta %></h4>

<%= link_to "editar", edit_admin_notice_path(@notice) %> |
<%= link_to "borrar", admin_notice_path(@notice), method: :delete , data: { confirma: "Estas seguro?"}%> |
<%= link_to "volver", admin_notices_path %>

proyectos/noticias/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noticias</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--Boostrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'shared/navbar' %> <!--Este es un componente-->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %>

    <%= flash.each do |nombre, mensaje| %>
      <%= mensaje %>
    <% end %>
8
  <%= yield %> <!-Aui empiezan mis vistas, entonces todo lo que venga antes me afecta a tooodas mis vistas-->

  </body>
</html>

proyectos/noticias/app/views/notices/index.html.erb
<!--Listado de noticias-->
<!--ver una noticia en particular-->
<!--Paso 13-->

<h1>TFC Smart</h1>
<h5>ESFOT-EPN</h5>

<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th>Nombre</th>
    <th>Cantidad</th>
    <th colspan="3">Accion</th>
  </tr>
  </thead>

  <tbody>
  <% @notices.each do |noticia| %>
    <tr>
      <td><%= noticia.titulo %></td>
      <td><%= noticia.descripcion_corta %></td>
      <td><%= noticia.descripcion_larga %></td>
      <td>
        <%= link_to "detalle", notice_path(noticia.slug) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<h4>Cantidad de noticias: <%= @notices.size %> </h4>
<!--
<h4>Agregar otra noticias: <%# link_to "nuevo", new_admin_notice_path %> </h4>
-->

proyectos/noticias/app/views/notices/show.html.erb
<h1>Detalle: </h1>
<h4><strong>Título: </strong><%= @notice.titulo %></h4>
<h4><strong>Descripcion: </strong><%= @notice.descripcion_corta %></h4>

<%= link_to "volver", notices_path %>

<h4>Comentarios: </h4>
<% if user_signed_in? %>
   formulario de para ingresar comentarios
  <%= form_with(model: @comentario, local: true) do |elemento| %><p>
      <%= elemento.hidden_field :user_id, value: current_user.id %>

      <%= elemento.hidden_field :notice_id, value: @notice.id  %>

      <%= elemento.label :comentarios %>
      <%= elemento.text_area :comentarios %>


    <%= elemento.submit "Guardar"  %>

  <% end %>
<% else %>
  Incia sesión para comentar :)
<% end %>

<div>
  Aquí debería ir la lista de comentarios... de todos..

  <table class="table table-striped">
    <thead class="thead-dark">
    <tr>
      <th>Usuario</th>
      <th colspan="3">Comentario</th>
    </tr>
    </thead>

    <tbody>
    <% @coment.each do |commentary| %>
      <tr>
        <td><%= commentary.user.email %></td> <!--user.campo-->
        <td><%= commentary.comentarios %></td><!--en mi bdd tengo este campo; es para un comentario individual-->
      </tr>
    <% end %>
    </tbody>
  </table>

</div>