proyectos/sistema_medico/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #El primer nombre "ethymons" es lo que va en el url www.algo/"algo" esto me va a llevar a la acción index del hospital_controller
  root 'ethymons#index' #Cualquier nombre:  sistema_medico..

  #Room
  get 'room', to: 'users#room'

  #Patienes
  resources :patients
  get 'stadistic', to: 'patients#stadistic'

  #Admin
  namespace :admin do
    resources :users
    get 'stadistic', to: 'users#stadistic'
  end

  #Visit
  resources :visits

end

proyectos/sistema_medico/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

proyectos/sistema_medico/app/models/patient.rb
class Patient < ApplicationRecord
  has_many :visits #cuantas visitas ha tendido el paciente
end

proyectos/sistema_medico/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # Creado po Devise
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable nadie se va a poder registar, solo iniciar sesion,
         :recoverable, :rememberable, :validatable

  has_many :patients #puedo contar user.patients para saber cuantos pacientes
  has_many :visits #cuantas visitas ha tenido un doctor

  #Tengo usuarios. tabla users, creado po Devise
  # cuadno creo un genearate devise User, crea una migracion con una tabla: users y el modelo, este modelo de aqui
  # luego hacemos una migracion rails db:migrate


end

proyectos/sistema_medico/app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user #doctor
  belongs_to :patient #visita pertenece a un paciente
end

proyectos/sistema_medico/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :validar_admin

  def stadistic
    @doctors = User.all
    @visits = Visit.all
    @patients = Patient.all

    @doctors_admin = User.where(administador: true)
    @doctors_only = User.where(administador: false)

    #@doctor_array = @doctors.map(& :id)
    #@visits_array = @visits.map(& :id)
    #@mayor = @doctors[1].visits.size;
    @mayor = 0;
    for each in @doctors
      actual =  each.visits.count
      if(each.visits.size > @mayor)
        @mayor = each.visits.size
      end
    end

    @frecuent = 0;
    for each in @patients
      actual =  each.visits.count
      if(each.visits.size > @frecuent)
        @frecuent = each.visits.size
      end
    end
  end

  def index
    @users = User.all
    @name = current_user.present? ? current_user.email : 'Desconocido'

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Registro Exitoso!" #Notice debe ir siempre, es un mensaje
      redirect_to admin_users_path
    else
      render 'new'
    end

  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Modificado con exito!"
      redirect_to admin_users_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id]) #solo los detalles del producto (id)
    @user.destroy
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :administador)
  end

  def validar_admin
    unless current_user.administador
      redirect_to root_path
    end
  end


end

proyectos/sistema_medico/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  #before_action :authenticate_user!

  protected

  def before_sign_in_path_for(resource)
    #current_user.is_a?(Admin) ? admin_tests_path : (stored_location_for(resource) || root_path)
    root_path
  end


  def after_sign_in_path_for(resource)
    #current_user.is_a?(Admin) ? admin_tests_path : (stored_location_for(resource) || root_path)
    room_path
  end


end

proyectos/sistema_medico/app/controllers/ethymons_controller.rb
class EthymonsController < ApplicationController

  def index
    @name = current_user.present? ? current_user.email : 'Desconocido'
  end

end

proyectos/sistema_medico/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!

    def stadistic
      @patient = current_user.patients
      @visit = current_user.visits
    end

    def new
      @patient = Patient.new
    end

    def create
      @patient = Patient.new(patient_params)

      if @patient.save
        flash[:notice] = "Registro Exitoso!" #Notice debe ir siempre, es un mensaje
        redirect_to room_path(@patient)
      else
        render 'new'
      end
    end

    def show
      @patient = Patient.find(params[:id])
      #A más de los pacientes, quiero que se me presenten las visitas.... pero de ése paciente
      @visit = Visit.new
      @visits = @patient.visits
    end

    def edit
      @patient = Patient.find(params[:id])
    end

    def update
      @patient = Patient.find(params[:id])
      if @patient.update(patient_params)
        flash[:notice] = "Modificado con exito!"
        redirect_to room_path(@patient)
      else
        render 'edit'
      end
    end

    def destroy
      @patient = Patient.find(params[:id]) #solo los detalles del producto (id)
      @patient.destroy
      redirect_to room_path
    end

    private
    def patient_params
      params.require(:patient).permit(:user_id, :ci, :name, :age, :height, :tblood, :allergy)
    end

    def find_visit
      @patient = Patient.find(params[:id])
    end


end

proyectos/sistema_medico/app/controllers/users_controller.rb
class UsersController < ApplicationController
  #Por defecto, asumiremos que todos los usuarios de la plataforma son doctores
  before_action :authenticate_user!
  def room

    #@patient = Patient.where(user_id: current_user.id)
    @patient = current_user.patients
  end


end

proyectos/sistema_medico/app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def show
    @visit = Visit.all

  end

  def new
    @visit = Visit.new
    @current_patient = Patient.find(params[:id])
    @patient =  @current_patient.visit

  end

  def create
    @visit = Visit.new(visit_params)

    if @visit.save
      flash[:notice] = "Registro Exitoso!" #Notice debe ir siempre, es un mensaje
      redirect_to patient_path(@visit.patient) #Esto me redirecciona al new (
      #(admin) si este método está dentro de un cotrolador para admin
    else
      render 'new'
    end

  end

  def edit
    @visit = Visit.find(params[:id]) #solo los detalles del producto (id)

  end

  def update
    @visit = Visit.find(params[:id]) #solo los detalles del producto (id)
    if @visit.update(visit_params)
      flash[:notice] = "Modificado con exito!"
      redirect_to room_path(@visit)
    else
      render 'edit'
    end
  end

  def destroy
    @visit = Visit.find(params[:id]) #solo los detalles del producto (id)
    @visit.destroy
    redirect_to room_path(@visit)
  end

  private
  def visit_params
    params.require(:visit).permit(:user_id, :patient_id, :fecha, :motive, :diagnostic)
  end

end

proyectos/sistema_medico/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

proyectos/sistema_medico/app/helpers/application_helper.rb
module ApplicationHelper
end

proyectos/sistema_medico/app/helpers/ethymons_helper.rb
module EthymonsHelper
end

proyectos/sistema_medico/app/helpers/patient/visits_helper.rb
module Patient::VisitsHelper
end

proyectos/sistema_medico/app/helpers/patients_helper.rb
module PatientsHelper
end

proyectos/sistema_medico/app/helpers/users_helper.rb
module UsersHelper
end

proyectos/sistema_medico/app/views/patients/edit.html.erb
<!--Crear es muy similar a editar, me traigo lo mismo-->
<h1>Edita un paciente</h1>

<% if @patient.errors.any? %>
  <h4>Hubo errores con la editación, revisa que...</h4>
  <ul>
    <% @patient.errors.full_messages.each do |errores| %>
      <li><%= errores %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for(@patient, html: {class:"col-s12" })  do |elemento| %>


  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :Cédula %>
    </div>
    <div class="col-1">
      <%= elemento.text_field :ci %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :Nombre %>
    </div>
    <div class="col-1">
      <%= elemento.text_field :name %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :Edad %>
    </div>
    <div class="col-1">
      <%= elemento.text_field :age %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :Peso %>
    </div>
    <div class="col-1">
      <%= elemento.text_field :height %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :TipoSangre %>
    </div>
    <div class="col-1">
      <%= elemento.text_field :tblood %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :Alergia %>
    </div>
    <div class="col-1">
      <%= elemento.text_field :allergy %>
    </div>
  </div>

  <br>
  <%= elemento.submit "Guardar", class: "btn btn-warning"   %>
  <%= link_to "Cancelar", room_path, class: "btn btn-danger" %>

<% end %>

proyectos/sistema_medico/app/views/patients/new.html.erb
<h1>Registro de nuevo paciente</h1>

<% if @patient.errors.any? %>
  <h4>Hubo errores con el registro, revisa que...</h4>
  <ul>
    <% @patient.errors.full_messages.each do |errores| %>
      <li><%= errores %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@patient, html: {class:"col-s12" })  do |elemento| %>

  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :Doctor %>
    </div>
    <div class="col-1">
      <%= elemento.hidden_field :user_id, value: current_user.id  %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :Cédula %>
    </div>
    <div class="col-1">
      <%= elemento.text_field :ci %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :Nombre %>
    </div>
    <div class="col-1">
      <%= elemento.text_field :name %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :Edad %>
    </div>
    <div class="col-1">
      <%= elemento.text_field :age %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :Peso %>
    </div>
    <div class="col-1">
      <%= elemento.text_field :height %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :TipoSangre %>
    </div>
    <div class="col-1">
      <%= elemento.text_field :tblood %>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class="col-1">
      <%= elemento.label :Alergia %>
    </div>
    <div class="col-1">
      <%= elemento.text_field :allergy %>
    </div>
  </div>

  <br>
  <%= elemento.submit "Guardar", class: "btn btn-warning"  %>
  <%= link_to "Cancelar", room_path, class: "btn btn-danger" %>

<% end %>

proyectos/sistema_medico/app/views/patients/show.html.erb
<h1>Detalle del paciente </h1>

<div class="row">
  <div class="col-3">
    <%= form_for(@patient, html: {class:"col-s12" })  do |elemento| %>

      <div class="row justify-content-start">
        <div class="col-3">
          <%= elemento.label :Doctor %>
        </div>
        <div class="col-3">
          <%= elemento.label :user_id, value: current_user.id, :disabled => true   %>
        </div>
      </div>

      <div class="row justify-content-start">
        <div class="col-3">
          <%= elemento.label :Cédula %>
        </div>
        <div class="col-3">
          <%= elemento.text_field :ci, :disabled => true %>
        </div>
      </div>

      <div class="row justify-content-start">
        <div class="col-3">
          <%= elemento.label :Nombre %>
        </div>
        <div class="col-3">
          <%= elemento.text_field :name, :disabled => true %>
        </div>
      </div>

      <div class="row justify-content-start">
        <div class="col-3">
          <%= elemento.label :Edad %>
        </div>
        <div class="col-3">
          <%= elemento.text_field :age, :disabled => true %>
        </div>
      </div>

      <div class="row justify-content-start">
        <div class="col-3">
          <%= elemento.label :Peso %>
        </div>
        <div class="col-3">
          <%= elemento.text_field :height, :disabled => true %>
        </div>
      </div>

      <div class="row justify-content-start">
        <div class="col-3">
          <%= elemento.label :TipoSangre %>
        </div>
        <div class="col-3">
          <%= elemento.text_field :tblood, :disabled => true %>
        </div>
      </div>

      <div class="row justify-content-start">
        <div class="col-3">
          <%= elemento.label :Alergia %>
        </div>
        <div class="col-3">
          <%= elemento.text_field :allergy, :disabled => true %>
        </div>
      </div>

      <br>
      <%= link_to "Editar", edit_patient_path, class: "btn btn-primary"  %>
      <%= link_to "Borrar", patient_path(elemento), method: :delete, data: { confirma: "Estas seguro?"} , class: "btn btn-danger"  %>
      <%= link_to "Volver", room_path, class: "btn btn-warning" %>
    <% end %>
  </div>

  <div class="col-9">
    <h3>Nueva visita: </h3>
    <div class="row">
      <div class="col-12">
        <%= form_for(@visit, html:{class: "col s12"}) do |elemento| %>

          <div class="row justify-content-start">
            <div class="col-1">
              <%= elemento.label :Doctor%>
            </div>
            <div class="col-1">
              <%= elemento.text_field :user_id, value: current_user.id %>
            </div>
          </div>

          <div class="row justify-content-start">
            <div class="col-1">
              <%= elemento.label :Paciente %>
            </div>
            <div class="col-1">
              <%= elemento.text_field :patient_id, value: @patient.id %>
            </div>
          </div>

          <div class="row justify-content-start">
            <div class="col-1">
              <%= elemento.label :Motivo %>
            </div>
            <div class="col-1">
              <%= elemento.text_field :motive %>
            </div>
          </div>

          <div class="row justify-content-start">
            <div class="col-1">
              <%= elemento.label :Diagnostico %>
            </div>
            <div class="col-1">
              <%= elemento.text_field :diagnostic %>
            </div>
          </div>

          <br>
          <%= elemento.submit "Guardar", class: "btn btn-primary"   %>
          <%= link_to "volver", room_path, class: "btn btn-warning" %>
        <% end %>
      </div>
    </div>

  </div>

</div>


<div class="row">
  <% @visits.each do |visit| %>
    <div class="col-3">
      <div class="card border-success mb-3" style="max-width: 18rem;">
        <div class="card-header bg-transparent border-success">Fecha: <%= visit.created_at %></div>
        <div class="card-body text-secondary">
          <h5 class="card-title"><%= visit.motive %></h5>
          <p class="card-text"><%= visit.diagnostic %></p>

          <%= link_to "editar", edit_visit_path, class: "btn btn-warning" %>
          <%= link_to "borrar", visit_path(visit), class: "btn btn-danger" , method: :delete , data: { confirm: "Estas seguro?"}%>

        </div>
        <div class="card-footer bg-transparent border-success">Doctor: <%= visit.user.email %></div>
      </div>
    </div>
  <% end %>
</div>

proyectos/sistema_medico/app/views/patients/stadistic.html.erb
<h2>Estadisticas de pacientes</h2>




<p>Número de pacientes: <%= @patient.size %></p>
<p>Número de visitas: <%= @visit.size %></p>
<!--
<p>Alergia más comun: </p>

-->

proyectos/sistema_medico/app/views/users/room.html.erb
<h1>Sala de espera :) </h1>
<br>
<br>

  <%= link_to 'Registrar nuevo paciente', new_patient_path, class: "btn btn-primary" %>
  <%= link_to 'Estadisticas', stadistic_path, class: "btn btn-danger" %>

<br>
<br>
<h5>Lista de Pacientes</h5>

<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th>Nombre</th>
    <th>Edad</th>
    <th>Peso</th>
    <th>Sangre</th>
    <th>Alergia</th>
    <th colspan="3">Accion</th>
  </tr>
  </thead>

  <tbody>
  <% @patient.each do |pat| %>
    <tr>
      <td><%= pat.name %></td>
      <td><%= pat.age %></td>
      <td><%= pat.height %></td>
      <td><%= pat.tblood %></td>
      <td><%= pat.allergy %></td>
      <td>
        <%= link_to "Detalle", patient_path(pat.id) %>
        <%= link_to "Editar", edit_patient_path(pat) %>
        <%= link_to "Borrar", patient_path(pat), method: :delete, data: { confirm: "Estas seguro?"}  %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<h6><%= link_to "volver", root_path, class: "btn btn-warning"  %></h6>